TuHotelEnLinea/Controllers/ExtrasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TuHotelEnLinea.Configuration;
using TuHotelEnLinea.Data;
using TuHotelEnLinea.Models;

namespace TuHotelEnLinea.Controllers
{
    public class ExtrasController : Controller
    {
        private readonly TuHotelEnLineaContext _context;
        private readonly IUnitOfWork _unitOfWork;
        public ExtrasController(TuHotelEnLineaContext context, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }

        // GET: Extras
        public async Task<IActionResult> Index()
        {
            return View(await _unitOfWork.ExtraRepository.GetAllAsync());
        }

        // GET: Extras/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null || _context.Extra == null)
            {
                return NotFound();
            }

            var extra = await _unitOfWork.ExtraRepository.GetByIdAsync(id);
            if (extra == null)
            {
                return NotFound();
            }

            return View(extra);
        }

        // GET: Extras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Extras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExtraId,ExtraName,ExtraDescription")] Extra extra)
        {

            _unitOfWork.ExtraRepository.Add(extra);
            _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));

        }

        // GET: Extras/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Extra == null)
            {
                return NotFound();
            }

            var extra = await _unitOfWork.ExtraRepository.GetByIdAsync(id);
            if (extra == null)
            {
                return NotFound();
            }
            return View(extra);
        }

        // POST: Extras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExtraId,ExtraName,ExtraDescription")] Extra extra)
        {
            if (id != extra.ExtraId)
            {
                return NotFound();
            }


            try
            {
                _unitOfWork.ExtraRepository.Update(extra);
                _unitOfWork.Commit();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ExtraExists(extra.ExtraId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Extras/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.Extra == null)
            {
                return NotFound();
            }

            var extra = await _unitOfWork.ExtraRepository.GetByIdAsync(id);
            if (extra == null)
            {
                return NotFound();
            }

            return View(extra);
        }

        // POST: Extras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Extra == null)
            {
                return Problem("Entity set 'TuHotelEnLineaContext.Extra'  is null.");
            }

            _unitOfWork.ExtraRepository.Delete(id);
            _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));
        }

        private bool ExtraExists(int id)
        {
            return _unitOfWork.ExtraRepository.GetByIdAsync(id) != null;
        }
    }
}

TuHotelEnLinea/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TuHotelEnLinea.Configuration;
using TuHotelEnLinea.Data;
using TuHotelEnLinea.Models;

namespace TuHotelEnLinea.Controllers
{
    public class RoomsController : Controller
    {
        private readonly TuHotelEnLineaContext _context;
        private readonly IUnitOfWork _unitOfWork;

        public RoomsController(TuHotelEnLineaContext context, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {

            return View(await _unitOfWork.RoomRepository.GetAllAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room = await _unitOfWork.RoomRepository.GetByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            ViewData["CategoryRoomId"] = new SelectList(_context.CategoryRoom, "CategoryRoomId", "CategoryRoomDescription");
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoomId,CategoryRoomId,RoomNum,RoomFloor,RoomQuota")] Room room)
        {

            _unitOfWork.RoomRepository.Add(room);
            _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));

        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room = await _unitOfWork.RoomRepository.GetByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["CategoryRoomId"] = new SelectList(_context.CategoryRoom, "CategoryRoomId", "CategoryRoomDescription", room.CategoryRoomId);
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoomId,CategoryRoomId,RoomNum,RoomFloor,RoomQuota")] Room room)
        {
            if (id != room.RoomId)
            {
                return NotFound();
            }


            try
            {
                _unitOfWork.RoomRepository.Update(room);
                _unitOfWork.Commit();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RoomExists(room.RoomId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room = await _unitOfWork.RoomRepository.GetByIdAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Room == null)
            {
                return Problem("Entity set 'TuHotelEnLineaContext.Room'  is null.");
            }
            _unitOfWork.RoomRepository.Delete(id);

            _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _unitOfWork.RoomRepository.GetByIdAsync(id) != null;
        }
    }
}

TuHotelEnLinea/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TuHotelEnLinea.Configuration;
using TuHotelEnLinea.Data;
using TuHotelEnLinea.Models;

namespace TuHotelEnLinea.Controllers
{
    public class SalesController : Controller
    {
        private readonly TuHotelEnLineaContext _context;
        private readonly IUnitOfWork _unitOfWork;
        public SalesController(TuHotelEnLineaContext context, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _context = context;
        }

        // GET: Sales
        public async Task<IActionResult> Index()
        {

            return View(await _unitOfWork.SalesRepository.GetAllAsync());
        }

        // GET: Sales/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null || _context.Sale == null)
            {
                return NotFound();
            }

            var sale = await _unitOfWork.SalesRepository.GetByIdAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // GET: Sales/Create
        public IActionResult Create()
        {
            ViewData["BookingId"] = new SelectList(_context.Booking, "BookingId", "BookingDate");
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethod, "PaymentMethodId", "PaymentMethodName");
            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaleId,SaleTotal,BookingId,PaymentMethodId")] Sale sale)
        {

            _unitOfWork.SalesRepository.Add(sale);
            _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));

        }

        // GET: Sales/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || _context.Sale == null)
            {
                return NotFound();
            }

            var sale = await _unitOfWork.SalesRepository.GetByIdAsync(id);
            if (sale == null)
            {
                return NotFound();
            }
            ViewData["BookingId"] = new SelectList(_context.Booking, "BookingId", "BookingDate", sale.BookingId);
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethod, "PaymentMethodId", "PaymentMethodName", sale.PaymentMethodId);
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SaleId,SaleTotal,BookingId,PaymentMethodId")] Sale sale)
        {
            if (id != sale.SaleId)
            {
                return NotFound();
            }


            try
            {
                _unitOfWork.SalesRepository.Update(sale);
                _unitOfWork.Commit();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SaleExists(sale.SaleId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Sales/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || _context.Sale == null)
            {
                return NotFound();
            }

            var sale = await _unitOfWork.SalesRepository.GetByIdAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sale == null)
            {
                return Problem("Entity set 'TuHotelEnLineaContext.Sale'  is null.");
            }
            _unitOfWork.SalesRepository.Delete(id);

            _unitOfWork.Commit();
            return RedirectToAction(nameof(Index));
        }

        private bool SaleExists(int id)
        {
            return  _unitOfWork.SalesRepository.GetByIdAsync(id) != null ;
        }
    }
}

TuHotelEnLinea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TuHotelEnLinea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TuHotelEnLinea.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TuHotelEnLinea</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">Booking</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryRooms" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customer</a>
                        </li>
                                               
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Extras" asp-action="Index">Extra</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Packages" asp-action="Index">Packages</a>
                        </li>
                                               
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PaymentMethods" asp-action="Index">Payment Methods</a>
                        </li>
                                               
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerXRooms" asp-action="Index">Customer x Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PackageExtras" asp-action="Index">Paquetes y Extras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TuHotelEnLinea - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>